const USER_TOKEN_EXPIRATION = 86400;
const ROLES = [ 'user', 'admin' ];
const DEFAULT_PAGINATION_LIMIT = 25;
const MAX_PAGINATION_LIMIT = 100;
const DEFAULT_PAGINATION_PAGE = 1;

module.exports = {
    ROLES,
    USER_TOKEN_EXPIRATION,
    DEFAULT_PAGINATION_LIMIT,
    MAX_PAGINATION_LIMIT,
    DEFAULT_PAGINATION_PAGE,
}